import os
import time

import tensorflow as tf

from tokenizer import (
    AstraTokenizer
)

from dataset import (
    make_sequences,
    make_dataset,
)
def _load_text(data_dir):
    """Load and combine all .txt files in data_dir."""
    if not os.path.isdir(data_dir):
        raise FileNotFoundError(
            f"Training data directory not found: {data_dir}"
        )

    files = sorted(
        f for f in os.listdir(data_dir)
        if f.lower().endswith(".txt")
    )

    if not files:
        raise FileNotFoundError(
            f"No .txt training files found in {data_dir}"
        )

    parts = []

    for filename in files:
        filepath = os.path.join(data_dir, filename)

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read().strip()

        if content:
            parts.append(content)

    if not parts:
        raise ValueError("All training files are empty.")

    return "\n\n".join(parts)


def _build_or_load_tokenizer(
    text,
    tokenizer_path,
    config
):
    """Load an existing tokenizer or build and save a new one."""

    if os.path.exists(tokenizer_path):
        print(f"Loading tokenizer: {tokenizer_path}")

        tokenizer = AstraTokenizer.load(tokenizer_path)

        print(
            f"Tokenizer loaded. Vocabulary: "
            f"{tokenizer.vocab_size}"
        )

        return tokenizer

    print("Building tokenizer...")

    vocab_size = int(config.get("vocab_size", 128))
    min_frequency = int(config.get("min_frequency", 1))

    tokenizer = AstraTokenizer(
        vocab_size=vocab_size,
        min_frequency=min_frequency,
    )

    tokenizer.train(text)

    tokenizer.save(tokenizer_path)

    print(
        f"Tokenizer saved: {tokenizer_path}"
    )
    print(
        f"Vocabulary: {tokenizer.vocab_size}"
    )

    return tokenizer


def _make_model(
    config,
    vocab_size
):
    """Create the Astra model using the same architecture as main.py."""

    from model import Astra

    model = Astra(
        vocab_size=vocab_size,
        seq=int(config["seq"]),
        d=int(config["d"]),
        layers=int(config["layers"]),
        heads=int(config["heads"]),
        ff=int(config["ff"]),
        dropout=float(config.get("dropout", 0.1)),
    )

    dummy = tf.zeros(
        (1, int(config["seq"])),
        dtype=tf.int32,
    )

    model(dummy, training=False)

    return model


def train(
    config,
    data_dir="data",
    tokenizer_path="tokenizer.json",
    checkpoint_dir="checkpoints/v5",
):
    """
    Astra V5 training entry point.

    Compatible with main.py:

        train(
            config=config,
            data_dir="data",
            tokenizer_path="tokenizer.json",
            checkpoint_dir="checkpoints/v5"
        )
    """

    # ---------------------------------------------------------
    # SETTINGS
    # ---------------------------------------------------------

    seq_len = int(config.get("seq", 64))
    stride = int(config.get("stride", max(1, seq_len // 2)))
    batch_size = int(config.get("batch", 16))
    epochs = int(config.get("epochs", 30))
    learning_rate = float(config.get("lr", 3e-4))
    shuffle_buffer = int(
        config.get("shuffle_buffer", 5000)
    )
    weight_decay = float(
        config.get("weight_decay", 0.01)
    )

    # ---------------------------------------------------------
    # DATA
    # ---------------------------------------------------------

    text = _load_text(data_dir)

    tokenizer = _build_or_load_tokenizer(
        text,
        tokenizer_path,
        config,
    )

    tokens = tokenizer.encode(text)

    if len(tokens) <= seq_len:
        raise ValueError(
            f"Not enough training tokens ({len(tokens)}) "
            f"for sequence length {seq_len}."
        )

    # Number of windows generated by the stride dataset.
    sequence_count = (
        (len(tokens) - seq_len - 1) // stride
    ) + 1

    sequence_count = max(0, sequence_count)

    batch_count = (
        sequence_count + batch_size - 1
    ) // batch_size

    print()
    print("================================")
    print("        ASTRA V5 TRAINING")
    print("================================")
    print()
    print(f"Training characters: {len(text)}")
    print(f"Vocabulary: {tokenizer.vocab_size}")
    print(f"Training tokens: {len(tokens)}")
    print(f"Training sequences: {sequence_count}")
    print(f"Training batches per epoch: {batch_count}")

    # ---------------------------------------------------------
    # MODEL
    # ---------------------------------------------------------

    model = _make_model(
        config,
        tokenizer.vocab_size,
    )

    print(
        f"Parameters: {model.count_params()}"
    )

    print()
    print("================================")
    print("       TRAINING CONFIG")
    print("================================")
    print()
    print(f"epochs: {epochs}")
    print(f"batch size: {batch_size}")
    print(f"sequence length: {seq_len}")
    print(f"stride: {stride}")
    print(f"learning rate: {learning_rate}")
    print(f"vocabulary: {tokenizer.vocab_size}")
    print(f"parameters: {model.count_params()}")
    print()

    # ---------------------------------------------------------
    # DATASET
    # ---------------------------------------------------------

    sequences = make_sequences(
        tokens,
        sequence_length=seq_len,
        stride=stride,
    )
    
    dataset = make_dataset(
        sequences,
        batch_size=config["batch"],
        shuffle_buffer=config.get(
            "shuffle_buffer",
            5000
        )
    )

    # ---------------------------------------------------------
    # OPTIMIZER
    # ---------------------------------------------------------

    optimizer = tf.keras.optimizers.AdamW(
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        clipnorm=1.0,
    )

    loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True
    )

    # ---------------------------------------------------------
    # CHECKPOINT
    # ---------------------------------------------------------

    os.makedirs(
        checkpoint_dir,
        exist_ok=True,
    )

    checkpoint = tf.train.Checkpoint(
        model=model,
        optimizer=optimizer,
    )

    manager = tf.train.CheckpointManager(
        checkpoint,
        checkpoint_dir,
        max_to_keep=5,
    )

    # ---------------------------------------------------------
    # TRAIN STEP
    # ---------------------------------------------------------

    @tf.function
    def train_step(x, y):

        with tf.GradientTape() as tape:
            logits = model(
                x,
                training=True,
            )

            loss = loss_fn(
                y,
                logits,
            )

        gradients = tape.gradient(
            loss,
            model.trainable_variables,
        )

        optimizer.apply_gradients(
            zip(
                gradients,
                model.trainable_variables,
            )
        )

        return loss

    # ---------------------------------------------------------
    # TRAIN
    # ---------------------------------------------------------

    print("Starting training...")
    print()

    total_start = time.time()

    for epoch in range(1, epochs + 1):

        epoch_start = time.time()
        losses = []

        for batch in dataset:

            if isinstance(batch, (tuple, list)):
                if len(batch) != 2:
                    raise ValueError(
                        "Dataset must return exactly "
                        "(x, y)."
                    )

                x, y = batch

            elif isinstance(batch, dict):
                x = batch["x"]
                y = batch["y"]

            else:
                raise TypeError(
                    "Unsupported dataset batch type: "
                    f"{type(batch)}"
                )

            loss = train_step(x, y)

            losses.append(
                float(loss.numpy())
            )

        if not losses:
            raise RuntimeError(
                "No training batches were produced."
            )

        mean_loss = (
            sum(losses) / len(losses)
        )

        epoch_time = (
            time.time() - epoch_start
        )

        print(
            f"epoch {epoch}/{epochs} - "
            f"loss: {mean_loss:.4f} - "
            f"time: {epoch_time:.1f}s"
        )

        save_path = manager.save()

        print(
            f"checkpoint: {save_path}"
        )
        print()

    total_time = (
        time.time() - total_start
    )

    print("================================")
    print("       TRAINING COMPLETE")
    print("================================")
    print()
    print(
        f"total training time: "
        f"{total_time:.1f}s"
    )
    print(
        f"average epoch time: "
        f"{total_time / max(epochs, 1):.1f}s"
    )

    if manager.latest_checkpoint:
        print(
            f"saved checkpoint: "
            f"{manager.latest_checkpoint}"
        )

    print(
        f"saved tokenizer: "
        f"{tokenizer_path}"
    )

    return model, tokenizer
